<?php

namespace AppBundle\Repository;

/**
 * LOGINRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LOGINRepository extends \Doctrine\ORM\EntityRepository
{
}
